### ISSUE TITLE
Graceful kick when lobby owner quits the game/lobby

### ISSUE THREAD

**Issue by Chrometurtle** [henpemaz/Rain-Meadow#111]
When the lobby owner leaves the lobby or exits the game. gracefully kick the other players

**Comment by 6fears7** [comment]
We have logic for OnPlayerDisconnet to pass ownership of the world to another player and enable the game to continue instead of kicking players:
```
        public void OnPlayerDisconnect(OnlinePlayer player)
        {
            if (this is Lobby lobby && owner == player) // lobby owner has left
            {
                RainMeadow.Debug($"Lobby owner {player} left!!!");
                NewOwner(MatchmakingManager.instance.GetLobbyOwner());
            }
```

However, we should add implementation here when a player leaves to strip their character from the world similar to how they are removed in the Region Gates logic so they're not "ghosting". 

We will also want a real disconnect from the game so that #78 should be resolved.

**Comment by Chrometurtle** [comment]
related to #92 as well

**Comment by 6fears7** [comment]
Graceful kick is implemented now on lobby owner quit
