### ISSUE TITLE
Grabbing Reindeer Antlers Freezes Game for Other Players

### ISSUE THREAD

**Issue by 6fears7** [henpemaz/Rain-Meadow#146]
Reported by user who managed to complete the story campaign online.  

Link to convo: https://discord.com/channels/1094716194180841602/1094730628970320044/1230690077387128882

 TODO: Add logs to this issue.

**Comment by Chrometurtle** [comment]
Deer.PlayerInAntlers needs to be synced. Then added to player

**Comment by henpemaz** [comment]
I suspect player movement code might also be breaking things, when in "climbing" mode tries to access the climbed object field which isn't synched.

For deer this might be easy to solve since the deer are synched, but other instances of this which I'm pretty sure will happen with corruption ropes and 5p long neuron thinghies since those aren't synched it might be hard.

**Comment by youbitchoc** [comment]
no longer freezes the game, but deer seem to cause graphical issues

```
[Error  :RainMeadow] 16:52:01|168367|RainMeadow.ObjectHooks.Room_Update:Object post-update error for object Slugcat ID.-1.2832 in room LF_H01
[Error  :RainMeadow] 16:52:01|168367|RainMeadow.ObjectHooks.Room_Update:System.NullReferenceException: Object reference not set to an instance of an object
  at SlugcatHand.EngageInMovement () [0x01630] in <a117a2e773414632b51933d2ae7f2aca>:0 
  at SlugcatHand.Update () [0x002b5] in <a117a2e773414632b51933d2ae7f2aca>:0 
  at PlayerGraphics.Update () [0x03371] in <a117a2e773414632b51933d2ae7f2aca>:0 
  at RainMeadow.RainMeadow+<>c.<Room_Update>b__135_15 (Room room, UpdatableAndDeletable uad) [0x00025] in /Game/RainMeadow.ObjectHooks.cs:88 
```

**Comment by youbitchoc** [comment]
will be fixed by https://github.com/henpemaz/Rain-Meadow/pull/496
